name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container: cypress/browsers:node16.14.0-chrome99-ff97
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: actions/setup-node@v3
        with:
          build: npm run build
          start: npx cypress lightBox/cypress/integration/3-test-lightbox
        
